version: '3.8'

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: notification-postgres
    environment:
      POSTGRES_DB: notification_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notification-network

  notification-service:
    image: notification-service:latest
    container_name: notification-service
    env_file:
      - production.env
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/notification-system.json:/app/classes/notification-system.json:ro
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - notification-network

  caddy:
    image: caddy:2-alpine
    container_name: notification-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - notification-service
    networks:
      - notification-network

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  notification-network:
    driver: bridge
